apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    role: {{ .Values.proxy.role }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  {{- if .Values.proxy.updateStrategy }}
  strategy:
    type: {{ .Values.proxy.updateStrategy.type }}
  {{- end }}
  selector:
    matchLabels:
      role: {{ .Values.proxy.role }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        role: {{ .Values.proxy.role }}
    spec:
      serviceAccountName: {{ .Values.proxy.serviceAccountName }}
      initContainers:
        - name: wait-for-secret
          image: {{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              for i in $(seq 1 120); do
                kubectl get secret -n {{ .Release.Namespace }} {{ .Values.proxyCertificate.secretName }} && exit 0
                echo "Waiting for secret {{ .Values.proxyCertificate.secretName }}..."
                sleep 5
              done
              echo "Timed out waiting for secret"
              exit 1
      containers:
      - name: main
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        env: {{ toYaml .Values.proxy.env | nindent 8 }}
        resources: {{ toYaml .Values.proxy.resources | nindent 10 }}
        ports:
        - name: metrics
          containerPort: {{ .Values.proxy.ports.metrics }}
          protocol: TCP
        - name: proxy
          containerPort: {{ .Values.proxy.ports.proxy }}
          protocol: TCP
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: configs
          mountPath: /configs
      volumes:
      - name: certs
        secret:
          secretName: {{ .Values.proxyCertificate.secretName }}
      - name: configs
        configMap:
          name: {{ .Release.Name }}-config
{{- with .Values.proxy.tolerations }}
      tolerations: {{ toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.proxy.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
{{- end }}
