apiVersion: v2
name: ergo-node
description: Ergo protocol description & reference client implementation
version: 0.3.1
appVersion: v6.1.0
maintainers:
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
