apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openvpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        config-checksum: {{ toJson .Values.configFiles | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "openvpn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openvpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENABLE_NAT
              value: "{{ if .Values.nat.enabled }}1{{ else }}0{{ end }}"
            - name: NAT_SOURCE
              value: "{{ .Values.nat.source }}"
            - name: NAT_DEVICE
              value: "{{ .Values.nat.device }}"
          ports:
            - name: ovpn
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - grep -q openvpn /proc/1/cmdline
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if (or .Values.configFiles .Values.startupScript .Values.metrics.enabled) }}
          volumeMounts:
            {{- range $idx, $config := .Values.configFiles }}
            - name: config-{{ $idx }}
              mountPath: /etc/openvpn/{{ $config.name }}
              {{- if $config.configMapName }}
              {{-   if $config.configMapKey }}
              subPath: {{ $config.configMapKey }}
              {{-   end }}
              {{- else }}
              subPath: {{ $config.name }}
              {{- end }}
            {{- end }}
            {{- if .Values.startupScript }}
            - name: startup-script
              mountPath: /usr/local/bin/entrypoint-user.sh
              subPath: entrypoint-user.sh
            {{- end }}
            {{- if .Values.metrics.enabled }}
            - name: status-file-dir
              mountPath: {{ dir .Values.metrics.statusFile }}
            {{- end }}
          {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
          imagePullPolicy: {{ .Values.metrics.image.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.metrics.securityContext | nindent 12 }}
          env:
            - name: OPENVPN_LISTEN_ADDRESS
              value: ":{{ .Values.metrics.port }}"
            - name: OPENVPN_STATUS_FILES
              value: {{ .Values.metrics.statusFile }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          resources: {{- toYaml .Values.metrics.resources | nindent 12 }}
          volumeMounts:
            - name: status-file-dir
              mountPath: {{ dir .Values.metrics.statusFile }}
        {{- end }}
        {{- if .Values.bind.enabled }}
        - name: bind
          image: "{{ .Values.bind.image.repository }}:{{ .Values.bind.image.tag }}"
          imagePullPolicy: {{ .Values.bind.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ALLOW_QUERY
              value: $(POD_IP)/32,127.0.0.1,10.8.0.0/24
            - name: ALLOW_RECURSION
              value: $(POD_IP)/32,127.0.0.1,10.8.0.0/24
            {{- if .Values.bind.env.dns_forwarder }}
            - name: DNS_FORWARDER
              value: {{ .Values.bind.env.dns_forwarder }}
            {{- end }}
            {{- if .Values.bind.env.extra_hosts }}
            - name: DNS_A
              value: {{ .Values.bind.env.extra_hosts }}
            {{- end }}
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          resources: {{- toYaml .Values.bind.resources | nindent 12 }}
      {{- end }}
      {{- if (or .Values.configFiles .Values.startupScript .Values.metrics.enabled) }}
      volumes:
        {{- range $idx, $config := .Values.configFiles }}
        - name: config-{{ $idx }}
          {{- if $config.configMapName }}
          configMap:
            name: {{ $config.configMapName }}
          {{- else if $config.secret | default false }}
          secret:
            secretName: {{ include "openvpn.fullname" $ }}-config-{{ $idx }}
          {{- else }}
          configMap:
            name: {{ include "openvpn.fullname" $ }}-config-{{ $idx }}
          {{- end }}
        {{- end }}
        {{- if .Values.startupScript }}
        - name: startup-script
          configMap:
            name: {{ include "openvpn.fullname" $ }}-config-startup-script
            defaultMode: 493 # 0755
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: status-file-dir
          emptyDir: {}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
