{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.podMonitor.fallbackScrapeProtocol }}
  fallbackScrapeProtocol: {{ . | quote }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wireguard.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    {{- toYaml .Values.podMonitor.podMetricsEndpoints | nindent 4 }}
{{- end }}
