apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}-api
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
  {{- with .Values.apiService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiService.type }}
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
