---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kupo.serviceAccountName" . }}
  labels:
    {{- include "kupo.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kupo.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kupo.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
