---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kupo.serviceAccountName" . }}
  labels:
    {{- include "kupo.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch"]
