apiVersion: v2
name: openvpn
description: A Helm chart for deploying OpenVPN in Kubernetes with an optional BIND sidecar
type: application
version: 0.9.0
appVersion: "2.6.3"

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
