apiVersion: v2
name: bursa
description: "A Helm chart for deploying Bursa"
version: 0.0.6
appVersion: 0.11.1

sources:
  - https://github.com/blinklabs-io/bursa

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
