apiVersion: v2
name: cardano-node
description: Creates a Cardano node deployment with SOCAT sidecar
version: 0.6.5
appVersion: 10.5.3
maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
