apiVersion: v2
name: tx-submit-api
description: Creates a Cardano Tx Submit API deployment
version: 0.1.19
appVersion: 0.20.9
maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
