apiVersion: v2
name: wireguard
description: WireGuard VPN server with JWT-authenticated peer management API
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
sources:
  - https://github.com/blinklabs-io/docker-wireguard
keywords:
  - wireguard
  - vpn
  - dvpn
  - cardano
