apiVersion: v2
name: dolos
description: Dolos server
version: 0.3.1
appVersion: "0.32.0"

sources:
  - https://github.com/txpipe/dolos

maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
