---
{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cardano-node.fullname" . }}
  labels:
    {{- include "cardano-node.labels" . | nindent 4 }}
{{- with .Values.podMonitor.extraLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .Values.podMonitor.fallbackScrapeProtocol }}
  fallbackScrapeProtocol: {{ . | quote }}
{{- end }}
{{- with .Values.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "cardano-node.matchLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    {{- toYaml .Values.podMonitor.podMetricsEndpoints | nindent 4 }}
{{- end }}
