apiVersion: v2
name: handshake-node
description: Deploys a Handshake node for specified network and a prometheus exporter for metrics
version: 0.2.1
appVersion: 8.0.0
maintainers:
  - name: aurora
    email: aurora@blinklabs.io
  - name: verbotenj
    email: verbotenj@blinklabs.io
  - name: wolf31o2
    email: wolf31o2@blinklabs.io
  - name: overcookedpanda
    email: overcookedpanda@blinklabs.io
