apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dolos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    cardano.demeter.run/network: {{ .Values.network }}
spec:
  clusterIP: None  # Headless service
  selector: {{- include "dolos.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.ports.grpc }}
    - name: ouroboros
      port: {{ .Values.service.ports.ouroboros }}
      targetPort: {{ .Values.ports.ouroboros }}
    - name: minibf
      port: {{ .Values.service.ports.minibf }}
      targetPort: {{ .Values.ports.minibf }}
