apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "dolos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    cardano.demeter.run/network: {{ .Values.network }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Values.service.name | default .Release.Name }}
  selector:
    matchLabels: {{- include "dolos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
          {{ toYaml .Values.podAnnotations | nindent 4 }}
        {{- end }}
      labels: {{- include "dolos.selectorLabels" . | nindent 8 -}}
        {{- if .Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 -}}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 180
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: dolos-ipc
          emptyDir: {}
      initContainers:
        - name: init
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -c
            - /etc/config/dolos.toml
            - bootstrap
            - snapshot
            - --variant
            - full
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: data
              mountPath: /var/data
            - name: dolos-ipc
              mountPath: /ipc
      containers:
        - name: dolos
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -c
            - /etc/config/dolos.toml
            - daemon
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: data
              mountPath: /var/data
            - name: dolos-ipc
              mountPath: /ipc
          ports:
            - name: grpc
              containerPort: {{ .Values.ports.grpc }}
              protocol: TCP
            - name: minibf
              containerPort: {{ .Values.ports.minibf }}
              protocol: TCP
        - name: socat-ntc
          image: "{{ .Values.socat.image.repository }}:{{ .Values.socat.image.tag }}"
          imagePullPolicy: {{ .Values.socat.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: PORT
              value: "{{ .Values.ports.ouroboros }}"
          command:
            - sh
            - -c
            - socat TCP-LISTEN:${PORT},fork UNIX-CLIENT:/ipc/dolos.socket,ignoreeof
          ports:
            - name: socat-ntc
              containerPort: {{ .Values.ports.ouroboros }}
          resources:
            {{- toYaml .Values.socat.resources | nindent 12 }}
          volumeMounts:
            - name: dolos-ipc
              mountPath: /ipc
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName }}
        {{- end }}
