{{- if .Values.secrets.fxrates.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-fxrates
  labels: {{ include "butane-oracle.labels" . | nindent 4 }}
  annotations:
    checksum/data: {{ toJson .Values.secrets.fxrates.data | sha256sum }}
type: Opaque
data:
{{- range .Values.secrets.fxrates.data }}
  {{ .key }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
{{- if .Values.secrets.keys.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keys
  labels: {{ include "butane-oracle.labels" . | nindent 4 }}
  annotations:
    checksum/data: {{ toJson .Values.secrets.keys.data | sha256sum }}
type: Opaque
data:
{{- range .Values.secrets.keys.data }}
  {{- if .encodedValue }}
    {{ .key }}: {{ .encodedValue }}
  {{- else }}
    {{ .key }}: {{ .value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
